### ISSUE TITLE
Regression introduced by 54d3d00f9544cafa361151c09806394f2df98c45

### ISSUE THREAD

**Issue by sdimitro** [ptesarik/libkdumpfile#27]
Recently the automation in one of the libkdumpfile consumer programs started failing because it would encounter errors trying to compile the python bindings of the library. The error seems to be caused by a macro that used to exist in Python 2 but not in Python 3 (we use Python 3) - `Py_TPFLAGS_HAVE_NEWBUFFER`.
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -I/opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m -I/opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m  -Wno-unused-result -Wsign-compare  -DNDEBUG -g -fwrapv -O3 -Wall -g -O2 -MT kdumpfile.lo -MD -MP -MF .deps/kdumpfile.Tpo -c -o kdumpfile.lo kdumpfile.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I/opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m -I/opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -O2 -MT kdumpfile.lo -MD -MP -MF .deps/kdumpfile.Tpo -c kdumpfile.c  -fPIC -DPIC -o .libs/kdumpfile.o
kdumpfile.c:2045:8: error: ‘Py_TPFLAGS_HAVE_NEWBUFFER’ undeclared here (not in a function); did you mean ‘Py_TPFLAGS_HAVE_FINALIZE’?
      | Py_TPFLAGS_HAVE_NEWBUFFER, /* tp_flags */
Makefile:776: recipe for target 'kdumpfile.lo' failed
        ^~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: Leaving directory '/home/runner/work/sdb/sdb/libkdumpfile/python'
        Py_TPFLAGS_HAVE_FINALIZE
make[3]: *** [kdumpfile.lo] Error 1
Makefile:795: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
make[2]: Leaving directory '/home/runner/work/sdb/sdb/libkdumpfile/python'
Makefile:521: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/runner/work/sdb/sdb/libkdumpfile'
Makefile:428: recipe for target 'all' failed
##[error]Process completed with exit code 2.
```

@ptesarik I'm not sure how many consumers you have on your end that potentially use Python 2 (or how bad it would be to just get rid of that TPFLAG) that's why I decided to just open an issue and not a PR.

**Comment by ptesarik** [comment]
Python2 is dead, but I'd like to support some old SLE distributions that still use it as default. Anyway, I had to introduce the flag to fix a failure on Python2, but did not recheck with Python3. Fix should be trivial.

**Comment by ptesarik** [comment]
Commit 2e8cec44da fixes the issue on my build host.

**Comment by sdimitro** [comment]
Verified on my end that the fix works. Thank you for jumping on this so quickly Petr!
